---
- name: "Partition new volume {{ extra_volume }}"
  shell: "parted --script  -- /dev/{{ extra_volume }} mklabel gpt && parted --script --align optimal -- /dev/{{ extra_volume }} mkpart primary ext4 0% 100%"

- name: "Creating ext4 filesystem {{ extra_volume_number }}"
  shell: "mkfs.ext4 -L {{ mount_label }} /dev/{{ extra_volume_number }}"

- name: "Creating mount point {{ mount_point }}"
  shell: "mkdir {{ mount_point }}"

- name: Updating /etc/fstab
  shell: 'echo "LABEL={{ mount_label }} {{ mount_point }} ext4 defaults 0 0" | tee -a /etc/fstab > /dev/null'

- name: "Mounting /dev/{{ extra_volume_number }}"
  shell: "mount -av"

