---
- name: Check if conda is installed
  stat:
    path: "{{ conda_prefix }}/bin/conda"
  register: conda_exe

- block:
    - name: Download conda installer
      get_url:
        url: "https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Linux-x86_64.sh"
        dest: /tmp/miniforge3.sh
        mode: 0755

    - name: Install conda
      command:
        cmd: /tmp/miniforge3.sh -b -p {{ conda_prefix }}
        creates: "{{ conda_prefix }}/bin/conda"

    - name: Remove conda installer
      file:
        path: /tmp/miniforge3.sh
        state: absent
  when: not conda_exe.stat.exists

- name: Ensure Conda is initialised in general profile
  file:
    src: "{{ conda_prefix }}/etc/profile.d/conda.sh"
    dest: /etc/profile.d/conda.sh
    state: link

- name: Ensure Mamba is initialised in general profile
  file:
    src: "{{ conda_prefix }}/etc/profile.d/mamba.sh"
    dest: /etc/profile.d/mamba.sh
    state: link

- name: Update conda and base environment
  shell: |
    source /etc/profile.d/conda.sh
    conda activate base
    conda update -y --all -q
  args:
    executable: /bin/bash
  when: conda_update_base
