---
- name: OTP support
  include_tasks: otp_{{ ansible_distribution | lower }}.yml
  when: with_otp

- name: Create Jupyterhub directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0750'
  loop:
    - /var/jupyterhub
    - /etc/jupyterhub

- name: Create jupyterhub config
  shell: |
    source /etc/profile.d/conda.sh
    conda activate {{ conda_env_name }}
    jupyterhub --generate-config -f /etc/jupyterhub/jupyterhub_config.py
  args:
    executable: /bin/bash
    creates: /etc/jupyterhub/jupyterhub_config.py

- name: Configure jupyterhub with HTTPS
  blockinfile:
    path: /etc/jupyterhub/jupyterhub_config.py
    block: |
      c.JupyterHub.bind_url = 'https://:443'
      c.JupyterHub.ssl_key = '{{ ssl_key }}'
      c.JupyterHub.ssl_cert = '{{ ssl_cert }}'
      c.ConfigurableHTTPProxy.command = ['configurable-http-proxy', '--redirect-port', '80']
      c.Spawner.cmd = ['jupyterhub-singleuser', '--ContentsManager.allow_hidden=True']
      {% if morpheus is defined %}
      c.Authenticator.allowed_users = {'{{ morpheus.user.linuxUsername }}'}
      {% else %}
      c.Authenticator.allow_all = True
      {% endif %}
      {% if with_otp %}
      c.Authenticator.request_otp = True
      c.PAMAuthenticator.service = 'jupyterhub'
      {% endif %}
  notify:
    - Restart jupyterhub

- name: Create the systemd service for jupyterhub
  template:
    src: templates/jupyterhub.service.j2
    dest: /etc/systemd/system/jupyterhub.service
  notify:
    - Reload daemons
    - Restart jupyterhub

- name: Ensure jupyter service is up and enabled
  service:
    name: jupyterhub
    state: started
    enabled: yes

- name: Print Jupyter URL
  debug:
    msg: "Jupyter ready at https://{{ host_fqdn }}"